apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermgmt-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermgmt-webapp
  template:
    metadata:
      labels:
        app: usermgmt-webapp
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.31
          command:
            - sh
            - -c
            - |
              echo "Waiting for MySQL...";
              while ! nc -z mysql 3306; do sleep 1; done;
              echo "MySQL is ready"
      containers:
        - name: usermgmt-webapp
          image: motieno205/usermanagement:2.0.0
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_HOSTNAME
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_NAME
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_PASSWORD
