apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermgmt-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermgmt-webapp
  template:
    metadata:
      labels:
        app: usermgmt-webapp
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.31
          command:
            - sh
            - -c
            - |
              echo "Waiting for MySQL...";
              while ! nc -z mysql 3306; do sleep 1; done;
              echo "MySQL is ready"
      containers:
        - name: usermgmt-webapp
          image: motieno205/usermanagement:2.0.0
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOSTNAME
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: user_management
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: django_pass